config/routes.rb
GeohuntServer::Application.routes.draw do
    root :to => "home#index"
  
    resources :users
    resources :tokens

    match 'tracking/move_user/:user_id/:latitude/:longitude(/:format)' => 'tracking#move_user', 
                :constraints => { :latitude => /[^\/]+/, 
                :longitude => /[^\/]+/ }, 
                :defaults => {:format => :json}
    match 'tracking/:action/gps/:latitude/:longitude(/:format)', 
                :controller => 'tracking', 
                :constraints => { :latitude => /[^\/]+/, :longitude => /[^\/]+/ }, 
                :format => :json
    match 'tracking/:action/range/:latitude_from/:latitude_to/:longitude_from/:longitude_to(/:format)', 
                :controller => 'tracking', 
                :constraints => { :latitude_from => /[^\/]+/, :latitude_to => /[^\/]+/, :longitude_from => /[^\/]+/, :longitude_to => /[^\/]+/, }, 
                :format => :json
    match 'tracking/:action(/:id)', :controller => 'tracking', :format => :json
    
    match 'tokens/take/:user_id/:token_id' => 'tracking#take', :format => :json
    match 'tokens/drop/:token_id' => 'tracking#take', :format => :json
    
    match ':controller(/:action(/:id))(.:format)'
    
    

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :latitude, :longitude
  
  reverse_geocoded_by :latitude, :longitude
  
  has_many :user_tracks
  has_many :tokens
  
end

app/models/user_track.rb
class UserTrack < ActiveRecord::Base
  belongs_to :user
  attr_accessible :date, :latitude, :longitude
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def index
    end
    
end

app/controllers/tracking_controller.rb
#require 'geocoder'

class TrackingController < ApplicationController
    
    respond_to :json, :xml
    
    def move_user
        @user = User.find(params[:user_id])
        @user.latitude = params[:latitude]
        @user.longitude = params[:longitude]
        @user.save()
        
        @user.user_tracks.create(:date => DateTime.now, :latitude => @user.latitude, :longitude => @user.longitude)
        Token.update_all({:latitude => params[:latitude], :longitude => params[:longitude]}, {:user_id => @user})
        
        #@user.tokens.each do |token|
        #    token.latitude = params[:latitude]
        #    token.longitude = params[:longitude]
        #    token.save()
        #end
        
        respond_with(@user)
    end
    
    def show_users
        if gps_parametrized?
            respond_with(User.near([params[:latitude],params[:longitude]], 1000, { :units => :km })) 
        else
            respond_with(User.where(:latitude => params[:latitude_from]..params[:latitude_to], :longitude => params[:longitude_from]..params[:longitude_to]))
        end
    end
    
    def show_tokens
        if gps_parametrized?
            respond_with(Token.near([params[:latitude],params[:longitude]], 1000, { :units => :km }))
        else
            respond_with(Token.where(:latitude => params[:latitude_from]..params[:latitude_to], :longitude => params[:longitude_from]..params[:longitude_to]))
        end
    end
    
    def show_near_tokens
        respond_with(Token.near([params[:latitude],params[:longitude]], 1, { :units => :km }))
    end
    
    def show_user_track
        respond_with(User.find(params[:id]).user_tracks)
    end
    
    def show_token_track
        respond_with(Token.find(params[:id]).token_tracks) 
    end
    
    def take
        token = Token.find(params[:token_id])
        token.user = User.find(params[:user_id])
        token.save()
        
        respond_with(token)
    end

    def drop
        token = Token.find(params[:token_id])
        token.user = nil
        token.save()
        
        respond_with(token)
    end

    private
        def gps_parametrized?
            return params[:latitude].present? && params[:longitude].present? 
        end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracking_helper.rb
module TrackingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>GeoHunt - úvodní stránka</h1>
<div><%= link_to('Uživatelé', users_path) %></div>
<div><%= link_to('Pešky', tokens_path) %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GeohuntServer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="body">
    <%= yield %>
</div>

</body>
</html>

app/views/tracking/move_user.html.erb
<p>User <%= @user.username %> přesunut na pozici <%= @user.gps %></p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>GPS</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.latitude %>,<%= user.longitude %></td>
    <td><%= link_to 'Show', user %>
        <%= link_to 'Edit', edit_user_path(user) %>
        <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>

<div><%= link_to 'New User', new_user_path %></div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Gps:</b>
  <%= @user.latitude %>,<%= @user.longitude %>
</p>


<h2>Držené pešky</h2>
<table>
  <tr>
    <th>Název</th>
    <th>GPS</th>
    <th>Body</th>
  </tr>

<% @user.tokens.each do |token| %>
  <tr>
    <td><%= token.name %></td>
    <td><%= token.latitude %>, <%= token.longitude %></td>
    <td><%= token.points_count %>b/<%= token.points_interval %>s (<%= token.default_points_count %>b/<%= token.default_points_interval %>s)</td>
  </tr>
<% end %>
</table>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>